/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package oes.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the QuestionContentLink service. Represents a row in the &quot;oes_QuestionContentLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link oes.service.model.impl.QuestionContentLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link oes.service.model.impl.QuestionContentLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuestionContentLink
 * @see oes.service.model.impl.QuestionContentLinkImpl
 * @see oes.service.model.impl.QuestionContentLinkModelImpl
 * @generated
 */
@ProviderType
public interface QuestionContentLinkModel extends BaseModel<QuestionContentLink> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a question content link model instance should use the {@link QuestionContentLink} interface instead.
	 */

	/**
	 * Returns the primary key of this question content link.
	 *
	 * @return the primary key of this question content link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this question content link.
	 *
	 * @param primaryKey the primary key of this question content link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the question order of this question content link.
	 *
	 * @return the question order of this question content link
	 */
	public long getQuestionOrder();

	/**
	 * Sets the question order of this question content link.
	 *
	 * @param questionOrder the question order of this question content link
	 */
	public void setQuestionOrder(long questionOrder);

	/**
	 * Returns the ddm content ID of this question content link.
	 *
	 * @return the ddm content ID of this question content link
	 */
	public long getDdmContentId();

	/**
	 * Sets the ddm content ID of this question content link.
	 *
	 * @param ddmContentId the ddm content ID of this question content link
	 */
	public void setDdmContentId(long ddmContentId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		oes.service.model.QuestionContentLink questionContentLink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<oes.service.model.QuestionContentLink> toCacheModel();

	@Override
	public oes.service.model.QuestionContentLink toEscapedModel();

	@Override
	public oes.service.model.QuestionContentLink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}