/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package priv.barrow.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import priv.barrow.model.StudentTeacherLink;

import priv.barrow.service.StudentTeacherLinkLocalService;
import priv.barrow.service.persistence.ExamQuestionLinkPersistence;
import priv.barrow.service.persistence.QuestionRecordLinkFinder;
import priv.barrow.service.persistence.QuestionRecordLinkPersistence;
import priv.barrow.service.persistence.StudentTeacherLinkPersistence;
import priv.barrow.service.persistence.TeacherUserLinkFinder;
import priv.barrow.service.persistence.TeacherUserLinkPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the student teacher link local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link priv.barrow.service.impl.StudentTeacherLinkLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see priv.barrow.service.impl.StudentTeacherLinkLocalServiceImpl
 * @see priv.barrow.service.StudentTeacherLinkLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class StudentTeacherLinkLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements StudentTeacherLinkLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link priv.barrow.service.StudentTeacherLinkLocalServiceUtil} to access the student teacher link local service.
	 */

	/**
	 * Adds the student teacher link to the database. Also notifies the appropriate model listeners.
	 *
	 * @param studentTeacherLink the student teacher link
	 * @return the student teacher link that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public StudentTeacherLink addStudentTeacherLink(
		StudentTeacherLink studentTeacherLink) {
		studentTeacherLink.setNew(true);

		return studentTeacherLinkPersistence.update(studentTeacherLink);
	}

	/**
	 * Creates a new student teacher link with the primary key. Does not add the student teacher link to the database.
	 *
	 * @param studentId the primary key for the new student teacher link
	 * @return the new student teacher link
	 */
	@Override
	public StudentTeacherLink createStudentTeacherLink(long studentId) {
		return studentTeacherLinkPersistence.create(studentId);
	}

	/**
	 * Deletes the student teacher link with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param studentId the primary key of the student teacher link
	 * @return the student teacher link that was removed
	 * @throws PortalException if a student teacher link with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public StudentTeacherLink deleteStudentTeacherLink(long studentId)
		throws PortalException {
		return studentTeacherLinkPersistence.remove(studentId);
	}

	/**
	 * Deletes the student teacher link from the database. Also notifies the appropriate model listeners.
	 *
	 * @param studentTeacherLink the student teacher link
	 * @return the student teacher link that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public StudentTeacherLink deleteStudentTeacherLink(
		StudentTeacherLink studentTeacherLink) {
		return studentTeacherLinkPersistence.remove(studentTeacherLink);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(StudentTeacherLink.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return studentTeacherLinkPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link priv.barrow.model.impl.StudentTeacherLinkModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return studentTeacherLinkPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link priv.barrow.model.impl.StudentTeacherLinkModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return studentTeacherLinkPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return studentTeacherLinkPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return studentTeacherLinkPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public StudentTeacherLink fetchStudentTeacherLink(long studentId) {
		return studentTeacherLinkPersistence.fetchByPrimaryKey(studentId);
	}

	/**
	 * Returns the student teacher link with the primary key.
	 *
	 * @param studentId the primary key of the student teacher link
	 * @return the student teacher link
	 * @throws PortalException if a student teacher link with the primary key could not be found
	 */
	@Override
	public StudentTeacherLink getStudentTeacherLink(long studentId)
		throws PortalException {
		return studentTeacherLinkPersistence.findByPrimaryKey(studentId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(studentTeacherLinkLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(StudentTeacherLink.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("studentId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(studentTeacherLinkLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(StudentTeacherLink.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("studentId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(studentTeacherLinkLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(StudentTeacherLink.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("studentId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return studentTeacherLinkLocalService.deleteStudentTeacherLink((StudentTeacherLink)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return studentTeacherLinkPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the student teacher links.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link priv.barrow.model.impl.StudentTeacherLinkModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of student teacher links
	 * @param end the upper bound of the range of student teacher links (not inclusive)
	 * @return the range of student teacher links
	 */
	@Override
	public List<StudentTeacherLink> getStudentTeacherLinks(int start, int end) {
		return studentTeacherLinkPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of student teacher links.
	 *
	 * @return the number of student teacher links
	 */
	@Override
	public int getStudentTeacherLinksCount() {
		return studentTeacherLinkPersistence.countAll();
	}

	/**
	 * Updates the student teacher link in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param studentTeacherLink the student teacher link
	 * @return the student teacher link that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public StudentTeacherLink updateStudentTeacherLink(
		StudentTeacherLink studentTeacherLink) {
		return studentTeacherLinkPersistence.update(studentTeacherLink);
	}

	/**
	 * Returns the exam question link local service.
	 *
	 * @return the exam question link local service
	 */
	public priv.barrow.service.ExamQuestionLinkLocalService getExamQuestionLinkLocalService() {
		return examQuestionLinkLocalService;
	}

	/**
	 * Sets the exam question link local service.
	 *
	 * @param examQuestionLinkLocalService the exam question link local service
	 */
	public void setExamQuestionLinkLocalService(
		priv.barrow.service.ExamQuestionLinkLocalService examQuestionLinkLocalService) {
		this.examQuestionLinkLocalService = examQuestionLinkLocalService;
	}

	/**
	 * Returns the exam question link persistence.
	 *
	 * @return the exam question link persistence
	 */
	public ExamQuestionLinkPersistence getExamQuestionLinkPersistence() {
		return examQuestionLinkPersistence;
	}

	/**
	 * Sets the exam question link persistence.
	 *
	 * @param examQuestionLinkPersistence the exam question link persistence
	 */
	public void setExamQuestionLinkPersistence(
		ExamQuestionLinkPersistence examQuestionLinkPersistence) {
		this.examQuestionLinkPersistence = examQuestionLinkPersistence;
	}

	/**
	 * Returns the question record link local service.
	 *
	 * @return the question record link local service
	 */
	public priv.barrow.service.QuestionRecordLinkLocalService getQuestionRecordLinkLocalService() {
		return questionRecordLinkLocalService;
	}

	/**
	 * Sets the question record link local service.
	 *
	 * @param questionRecordLinkLocalService the question record link local service
	 */
	public void setQuestionRecordLinkLocalService(
		priv.barrow.service.QuestionRecordLinkLocalService questionRecordLinkLocalService) {
		this.questionRecordLinkLocalService = questionRecordLinkLocalService;
	}

	/**
	 * Returns the question record link persistence.
	 *
	 * @return the question record link persistence
	 */
	public QuestionRecordLinkPersistence getQuestionRecordLinkPersistence() {
		return questionRecordLinkPersistence;
	}

	/**
	 * Sets the question record link persistence.
	 *
	 * @param questionRecordLinkPersistence the question record link persistence
	 */
	public void setQuestionRecordLinkPersistence(
		QuestionRecordLinkPersistence questionRecordLinkPersistence) {
		this.questionRecordLinkPersistence = questionRecordLinkPersistence;
	}

	/**
	 * Returns the question record link finder.
	 *
	 * @return the question record link finder
	 */
	public QuestionRecordLinkFinder getQuestionRecordLinkFinder() {
		return questionRecordLinkFinder;
	}

	/**
	 * Sets the question record link finder.
	 *
	 * @param questionRecordLinkFinder the question record link finder
	 */
	public void setQuestionRecordLinkFinder(
		QuestionRecordLinkFinder questionRecordLinkFinder) {
		this.questionRecordLinkFinder = questionRecordLinkFinder;
	}

	/**
	 * Returns the student teacher link local service.
	 *
	 * @return the student teacher link local service
	 */
	public StudentTeacherLinkLocalService getStudentTeacherLinkLocalService() {
		return studentTeacherLinkLocalService;
	}

	/**
	 * Sets the student teacher link local service.
	 *
	 * @param studentTeacherLinkLocalService the student teacher link local service
	 */
	public void setStudentTeacherLinkLocalService(
		StudentTeacherLinkLocalService studentTeacherLinkLocalService) {
		this.studentTeacherLinkLocalService = studentTeacherLinkLocalService;
	}

	/**
	 * Returns the student teacher link persistence.
	 *
	 * @return the student teacher link persistence
	 */
	public StudentTeacherLinkPersistence getStudentTeacherLinkPersistence() {
		return studentTeacherLinkPersistence;
	}

	/**
	 * Sets the student teacher link persistence.
	 *
	 * @param studentTeacherLinkPersistence the student teacher link persistence
	 */
	public void setStudentTeacherLinkPersistence(
		StudentTeacherLinkPersistence studentTeacherLinkPersistence) {
		this.studentTeacherLinkPersistence = studentTeacherLinkPersistence;
	}

	/**
	 * Returns the teacher user link local service.
	 *
	 * @return the teacher user link local service
	 */
	public priv.barrow.service.TeacherUserLinkLocalService getTeacherUserLinkLocalService() {
		return teacherUserLinkLocalService;
	}

	/**
	 * Sets the teacher user link local service.
	 *
	 * @param teacherUserLinkLocalService the teacher user link local service
	 */
	public void setTeacherUserLinkLocalService(
		priv.barrow.service.TeacherUserLinkLocalService teacherUserLinkLocalService) {
		this.teacherUserLinkLocalService = teacherUserLinkLocalService;
	}

	/**
	 * Returns the teacher user link persistence.
	 *
	 * @return the teacher user link persistence
	 */
	public TeacherUserLinkPersistence getTeacherUserLinkPersistence() {
		return teacherUserLinkPersistence;
	}

	/**
	 * Sets the teacher user link persistence.
	 *
	 * @param teacherUserLinkPersistence the teacher user link persistence
	 */
	public void setTeacherUserLinkPersistence(
		TeacherUserLinkPersistence teacherUserLinkPersistence) {
		this.teacherUserLinkPersistence = teacherUserLinkPersistence;
	}

	/**
	 * Returns the teacher user link finder.
	 *
	 * @return the teacher user link finder
	 */
	public TeacherUserLinkFinder getTeacherUserLinkFinder() {
		return teacherUserLinkFinder;
	}

	/**
	 * Sets the teacher user link finder.
	 *
	 * @param teacherUserLinkFinder the teacher user link finder
	 */
	public void setTeacherUserLinkFinder(
		TeacherUserLinkFinder teacherUserLinkFinder) {
		this.teacherUserLinkFinder = teacherUserLinkFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("priv.barrow.model.StudentTeacherLink",
			studentTeacherLinkLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"priv.barrow.model.StudentTeacherLink");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return StudentTeacherLinkLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return StudentTeacherLink.class;
	}

	protected String getModelClassName() {
		return StudentTeacherLink.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = studentTeacherLinkPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = priv.barrow.service.ExamQuestionLinkLocalService.class)
	protected priv.barrow.service.ExamQuestionLinkLocalService examQuestionLinkLocalService;
	@BeanReference(type = ExamQuestionLinkPersistence.class)
	protected ExamQuestionLinkPersistence examQuestionLinkPersistence;
	@BeanReference(type = priv.barrow.service.QuestionRecordLinkLocalService.class)
	protected priv.barrow.service.QuestionRecordLinkLocalService questionRecordLinkLocalService;
	@BeanReference(type = QuestionRecordLinkPersistence.class)
	protected QuestionRecordLinkPersistence questionRecordLinkPersistence;
	@BeanReference(type = QuestionRecordLinkFinder.class)
	protected QuestionRecordLinkFinder questionRecordLinkFinder;
	@BeanReference(type = StudentTeacherLinkLocalService.class)
	protected StudentTeacherLinkLocalService studentTeacherLinkLocalService;
	@BeanReference(type = StudentTeacherLinkPersistence.class)
	protected StudentTeacherLinkPersistence studentTeacherLinkPersistence;
	@BeanReference(type = priv.barrow.service.TeacherUserLinkLocalService.class)
	protected priv.barrow.service.TeacherUserLinkLocalService teacherUserLinkLocalService;
	@BeanReference(type = TeacherUserLinkPersistence.class)
	protected TeacherUserLinkPersistence teacherUserLinkPersistence;
	@BeanReference(type = TeacherUserLinkFinder.class)
	protected TeacherUserLinkFinder teacherUserLinkFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}