/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package priv.barrow.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import priv.barrow.model.TeacherUserLink;
import priv.barrow.model.TeacherUserLinkModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TeacherUserLink service. Represents a row in the &quot;OES_TeacherUserLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TeacherUserLinkModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TeacherUserLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TeacherUserLinkImpl
 * @see TeacherUserLink
 * @see TeacherUserLinkModel
 * @generated
 */
@ProviderType
public class TeacherUserLinkModelImpl extends BaseModelImpl<TeacherUserLink>
	implements TeacherUserLinkModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a teacher user link model instance should use the {@link TeacherUserLink} interface instead.
	 */
	public static final String TABLE_NAME = "OES_TeacherUserLink";
	public static final Object[][] TABLE_COLUMNS = {
			{ "teacherNumber", Types.BIGINT },
			{ "userId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("teacherNumber", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table OES_TeacherUserLink (teacherNumber LONG not null primary key,userId LONG)";
	public static final String TABLE_SQL_DROP = "drop table OES_TeacherUserLink";
	public static final String ORDER_BY_JPQL = " ORDER BY teacherUserLink.teacherNumber ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OES_TeacherUserLink.teacherNumber ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(priv.barrow.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.priv.barrow.model.TeacherUserLink"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(priv.barrow.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.priv.barrow.model.TeacherUserLink"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(priv.barrow.service.util.ServiceProps.get(
				"lock.expiration.time.priv.barrow.model.TeacherUserLink"));

	public TeacherUserLinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _teacherNumber;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTeacherNumber(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _teacherNumber;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TeacherUserLink.class;
	}

	@Override
	public String getModelClassName() {
		return TeacherUserLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("teacherNumber", getTeacherNumber());
		attributes.put("userId", getUserId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long teacherNumber = (Long)attributes.get("teacherNumber");

		if (teacherNumber != null) {
			setTeacherNumber(teacherNumber);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}
	}

	@Override
	public long getTeacherNumber() {
		return _teacherNumber;
	}

	@Override
	public void setTeacherNumber(long teacherNumber) {
		_teacherNumber = teacherNumber;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TeacherUserLink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TeacherUserLink toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TeacherUserLink)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TeacherUserLinkImpl teacherUserLinkImpl = new TeacherUserLinkImpl();

		teacherUserLinkImpl.setTeacherNumber(getTeacherNumber());
		teacherUserLinkImpl.setUserId(getUserId());

		teacherUserLinkImpl.resetOriginalValues();

		return teacherUserLinkImpl;
	}

	@Override
	public int compareTo(TeacherUserLink teacherUserLink) {
		long primaryKey = teacherUserLink.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TeacherUserLink)) {
			return false;
		}

		TeacherUserLink teacherUserLink = (TeacherUserLink)obj;

		long primaryKey = teacherUserLink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<TeacherUserLink> toCacheModel() {
		TeacherUserLinkCacheModel teacherUserLinkCacheModel = new TeacherUserLinkCacheModel();

		teacherUserLinkCacheModel.teacherNumber = getTeacherNumber();

		teacherUserLinkCacheModel.userId = getUserId();

		return teacherUserLinkCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{teacherNumber=");
		sb.append(getTeacherNumber());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("priv.barrow.model.TeacherUserLink");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>teacherNumber</column-name><column-value><![CDATA[");
		sb.append(getTeacherNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = TeacherUserLink.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			TeacherUserLink.class
		};
	private long _teacherNumber;
	private long _userId;
	private TeacherUserLink _escapedModel;
}