/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package priv.barrow.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ExamQuestionLink service. Represents a row in the &quot;OES_ExamQuestionLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link priv.barrow.model.impl.ExamQuestionLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link priv.barrow.model.impl.ExamQuestionLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExamQuestionLink
 * @see priv.barrow.model.impl.ExamQuestionLinkImpl
 * @see priv.barrow.model.impl.ExamQuestionLinkModelImpl
 * @generated
 */
@ProviderType
public interface ExamQuestionLinkModel extends BaseModel<ExamQuestionLink> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a exam question link model instance should use the {@link ExamQuestionLink} interface instead.
	 */

	/**
	 * Returns the primary key of this exam question link.
	 *
	 * @return the primary key of this exam question link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this exam question link.
	 *
	 * @param primaryKey the primary key of this exam question link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the exam record ID of this exam question link.
	 *
	 * @return the exam record ID of this exam question link
	 */
	public long getExamRecordId();

	/**
	 * Sets the exam record ID of this exam question link.
	 *
	 * @param examRecordId the exam record ID of this exam question link
	 */
	public void setExamRecordId(long examRecordId);

	/**
	 * Returns the question record ID of this exam question link.
	 *
	 * @return the question record ID of this exam question link
	 */
	public long getQuestionRecordId();

	/**
	 * Sets the question record ID of this exam question link.
	 *
	 * @param questionRecordId the question record ID of this exam question link
	 */
	public void setQuestionRecordId(long questionRecordId);

	/**
	 * Returns the question record version of this exam question link.
	 *
	 * @return the question record version of this exam question link
	 */
	@AutoEscape
	public String getQuestionRecordVersion();

	/**
	 * Sets the question record version of this exam question link.
	 *
	 * @param questionRecordVersion the question record version of this exam question link
	 */
	public void setQuestionRecordVersion(String questionRecordVersion);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(priv.barrow.model.ExamQuestionLink examQuestionLink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<priv.barrow.model.ExamQuestionLink> toCacheModel();

	@Override
	public priv.barrow.model.ExamQuestionLink toEscapedModel();

	@Override
	public priv.barrow.model.ExamQuestionLink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}