/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package priv.barrow.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the QuestionRecordLink service. Represents a row in the &quot;OES_QuestionRecordLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link priv.barrow.model.impl.QuestionRecordLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link priv.barrow.model.impl.QuestionRecordLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuestionRecordLink
 * @see priv.barrow.model.impl.QuestionRecordLinkImpl
 * @see priv.barrow.model.impl.QuestionRecordLinkModelImpl
 * @generated
 */
@ProviderType
public interface QuestionRecordLinkModel extends BaseModel<QuestionRecordLink> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a question record link model instance should use the {@link QuestionRecordLink} interface instead.
	 */

	/**
	 * Returns the primary key of this question record link.
	 *
	 * @return the primary key of this question record link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this question record link.
	 *
	 * @param primaryKey the primary key of this question record link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the question order of this question record link.
	 *
	 * @return the question order of this question record link
	 */
	public long getQuestionOrder();

	/**
	 * Sets the question order of this question record link.
	 *
	 * @param questionOrder the question order of this question record link
	 */
	public void setQuestionOrder(long questionOrder);

	/**
	 * Returns the ddl record ID of this question record link.
	 *
	 * @return the ddl record ID of this question record link
	 */
	public long getDdlRecordId();

	/**
	 * Sets the ddl record ID of this question record link.
	 *
	 * @param ddlRecordId the ddl record ID of this question record link
	 */
	public void setDdlRecordId(long ddlRecordId);

	/**
	 * Returns the active of this question record link.
	 *
	 * @return the active of this question record link
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this question record link is active.
	 *
	 * @return <code>true</code> if this question record link is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this question record link is active.
	 *
	 * @param active the active of this question record link
	 */
	public void setActive(boolean active);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		priv.barrow.model.QuestionRecordLink questionRecordLink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<priv.barrow.model.QuestionRecordLink> toCacheModel();

	@Override
	public priv.barrow.model.QuestionRecordLink toEscapedModel();

	@Override
	public priv.barrow.model.QuestionRecordLink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}