/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package priv.barrow.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the StudentTeacherLink service. Represents a row in the &quot;OES_StudentTeacherLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link priv.barrow.model.impl.StudentTeacherLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link priv.barrow.model.impl.StudentTeacherLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StudentTeacherLink
 * @see priv.barrow.model.impl.StudentTeacherLinkImpl
 * @see priv.barrow.model.impl.StudentTeacherLinkModelImpl
 * @generated
 */
@ProviderType
public interface StudentTeacherLinkModel extends BaseModel<StudentTeacherLink> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student teacher link model instance should use the {@link StudentTeacherLink} interface instead.
	 */

	/**
	 * Returns the primary key of this student teacher link.
	 *
	 * @return the primary key of this student teacher link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student teacher link.
	 *
	 * @param primaryKey the primary key of this student teacher link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the student ID of this student teacher link.
	 *
	 * @return the student ID of this student teacher link
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this student teacher link.
	 *
	 * @param studentId the student ID of this student teacher link
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the teacher ID of this student teacher link.
	 *
	 * @return the teacher ID of this student teacher link
	 */
	public long getTeacherId();

	/**
	 * Sets the teacher ID of this student teacher link.
	 *
	 * @param teacherId the teacher ID of this student teacher link
	 */
	public void setTeacherId(long teacherId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		priv.barrow.model.StudentTeacherLink studentTeacherLink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<priv.barrow.model.StudentTeacherLink> toCacheModel();

	@Override
	public priv.barrow.model.StudentTeacherLink toEscapedModel();

	@Override
	public priv.barrow.model.StudentTeacherLink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}