/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package priv.barrow.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the TeacherUserLink service. Represents a row in the &quot;OES_TeacherUserLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link priv.barrow.model.impl.TeacherUserLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link priv.barrow.model.impl.TeacherUserLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TeacherUserLink
 * @see priv.barrow.model.impl.TeacherUserLinkImpl
 * @see priv.barrow.model.impl.TeacherUserLinkModelImpl
 * @generated
 */
@ProviderType
public interface TeacherUserLinkModel extends BaseModel<TeacherUserLink> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a teacher user link model instance should use the {@link TeacherUserLink} interface instead.
	 */

	/**
	 * Returns the primary key of this teacher user link.
	 *
	 * @return the primary key of this teacher user link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this teacher user link.
	 *
	 * @param primaryKey the primary key of this teacher user link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the teacher number of this teacher user link.
	 *
	 * @return the teacher number of this teacher user link
	 */
	public long getTeacherNumber();

	/**
	 * Sets the teacher number of this teacher user link.
	 *
	 * @param teacherNumber the teacher number of this teacher user link
	 */
	public void setTeacherNumber(long teacherNumber);

	/**
	 * Returns the user ID of this teacher user link.
	 *
	 * @return the user ID of this teacher user link
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this teacher user link.
	 *
	 * @param userId the user ID of this teacher user link
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this teacher user link.
	 *
	 * @return the user uuid of this teacher user link
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this teacher user link.
	 *
	 * @param userUuid the user uuid of this teacher user link
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(priv.barrow.model.TeacherUserLink teacherUserLink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<priv.barrow.model.TeacherUserLink> toCacheModel();

	@Override
	public priv.barrow.model.TeacherUserLink toEscapedModel();

	@Override
	public priv.barrow.model.TeacherUserLink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}