/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package oes.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import oes.service.model.QuestionContentLink;
import oes.service.model.QuestionContentLinkModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the QuestionContentLink service. Represents a row in the &quot;oes_QuestionContentLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link QuestionContentLinkModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QuestionContentLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuestionContentLinkImpl
 * @see QuestionContentLink
 * @see QuestionContentLinkModel
 * @generated
 */
@ProviderType
public class QuestionContentLinkModelImpl extends BaseModelImpl<QuestionContentLink>
	implements QuestionContentLinkModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a question content link model instance should use the {@link QuestionContentLink} interface instead.
	 */
	public static final String TABLE_NAME = "oes_QuestionContentLink";
	public static final Object[][] TABLE_COLUMNS = {
			{ "questionOrder", Types.BIGINT },
			{ "ddmContentId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("questionOrder", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ddmContentId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table oes_QuestionContentLink (questionOrder LONG not null primary key,ddmContentId LONG)";
	public static final String TABLE_SQL_DROP = "drop table oes_QuestionContentLink";
	public static final String ORDER_BY_JPQL = " ORDER BY questionContentLink.questionOrder ASC";
	public static final String ORDER_BY_SQL = " ORDER BY oes_QuestionContentLink.questionOrder ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(oes.service.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.oes.service.model.QuestionContentLink"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(oes.service.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.oes.service.model.QuestionContentLink"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(oes.service.service.util.ServiceProps.get(
				"lock.expiration.time.oes.service.model.QuestionContentLink"));

	public QuestionContentLinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _questionOrder;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setQuestionOrder(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _questionOrder;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QuestionContentLink.class;
	}

	@Override
	public String getModelClassName() {
		return QuestionContentLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("questionOrder", getQuestionOrder());
		attributes.put("ddmContentId", getDdmContentId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long questionOrder = (Long)attributes.get("questionOrder");

		if (questionOrder != null) {
			setQuestionOrder(questionOrder);
		}

		Long ddmContentId = (Long)attributes.get("ddmContentId");

		if (ddmContentId != null) {
			setDdmContentId(ddmContentId);
		}
	}

	@Override
	public long getQuestionOrder() {
		return _questionOrder;
	}

	@Override
	public void setQuestionOrder(long questionOrder) {
		_questionOrder = questionOrder;
	}

	@Override
	public long getDdmContentId() {
		return _ddmContentId;
	}

	@Override
	public void setDdmContentId(long ddmContentId) {
		_ddmContentId = ddmContentId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			QuestionContentLink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QuestionContentLink toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (QuestionContentLink)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QuestionContentLinkImpl questionContentLinkImpl = new QuestionContentLinkImpl();

		questionContentLinkImpl.setQuestionOrder(getQuestionOrder());
		questionContentLinkImpl.setDdmContentId(getDdmContentId());

		questionContentLinkImpl.resetOriginalValues();

		return questionContentLinkImpl;
	}

	@Override
	public int compareTo(QuestionContentLink questionContentLink) {
		int value = 0;

		if (getQuestionOrder() < questionContentLink.getQuestionOrder()) {
			value = -1;
		}
		else if (getQuestionOrder() > questionContentLink.getQuestionOrder()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof QuestionContentLink)) {
			return false;
		}

		QuestionContentLink questionContentLink = (QuestionContentLink)obj;

		long primaryKey = questionContentLink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<QuestionContentLink> toCacheModel() {
		QuestionContentLinkCacheModel questionContentLinkCacheModel = new QuestionContentLinkCacheModel();

		questionContentLinkCacheModel.questionOrder = getQuestionOrder();

		questionContentLinkCacheModel.ddmContentId = getDdmContentId();

		return questionContentLinkCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{questionOrder=");
		sb.append(getQuestionOrder());
		sb.append(", ddmContentId=");
		sb.append(getDdmContentId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("oes.service.model.QuestionContentLink");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>questionOrder</column-name><column-value><![CDATA[");
		sb.append(getQuestionOrder());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ddmContentId</column-name><column-value><![CDATA[");
		sb.append(getDdmContentId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = QuestionContentLink.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			QuestionContentLink.class
		};
	private long _questionOrder;
	private long _ddmContentId;
	private QuestionContentLink _escapedModel;
}