/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package oes.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import oes.service.model.QuestionContentLink;

import oes.service.service.QuestionContentLinkLocalServiceUtil;

/**
 * The extended model base implementation for the QuestionContentLink service. Represents a row in the &quot;oes_QuestionContentLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QuestionContentLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuestionContentLinkImpl
 * @see QuestionContentLink
 * @generated
 */
@ProviderType
public abstract class QuestionContentLinkBaseImpl
	extends QuestionContentLinkModelImpl implements QuestionContentLink {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a question content link model instance should use the {@link QuestionContentLink} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			QuestionContentLinkLocalServiceUtil.addQuestionContentLink(this);
		}
		else {
			QuestionContentLinkLocalServiceUtil.updateQuestionContentLink(this);
		}
	}
}